### ISSUE TITLE
Compile error: multiple definition of `spoolfile' error on Manjaro.  Compiles cleanly on Mint 20.

### ISSUE THREAD

**Issue by btammaster** [HeyuX10Automation/heyu#35] opened 2021-04-27 13:10 UTC
I've been using heyu for years on an old Manjaro box that died.  When I tried to install it on a newer Manjaro box, it got errors.  I tested it on an identical Mint box, and it installed cleanly.  I tried both Heyu 2.10.2 and Heyu 2.10.1 versions. 

gcc version 10.2.0 (GCC) is on the Manjaro box.

Pardon me for being a noob if I've missed something obvious.  Please let me know what other documentation I should be listing.  Thank you.

------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------

**This compiles cleanly on Mint 20:**

user1@I390:~/Downloads/heyu/heyu-2.10.2$ ./Configure

This script will create a Makefile based by default on
the output of uname(1), or otherwise on the system type
parameter you enter.
 
The Makefile has been created for linux.

Note: If you are upgrading from an earlier version,
run 'heyu stop' before proceeding further.

** Now run 'make' as a normal user **

user1@I390:~/Downloads/heyu/heyu-2.10.2$ make
(snip)
** Now become root and run 'make install' **

------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------

**When I attempt to compile on Manjaro, I get the following error:**

user1@R158:~/Downloads/Heyu/2.10.1/heyu-2.10.1$ make

or

user1@R158:~/Downloads/Heyu/2.10.1/heyu-2.10.1$ CFLAGS=-fcommon ./Configure && make

(snip)
gcc  -o heyu date.o erase.o info.o message.o relay.o monitor.o reset.o setclock.o stop.o tty.o x10.o xread.o xwrite.o status.o cm11a.o eeprom.o process.o sun.o cmd.o config.o x10state.o poll.o modules.o cm17a.o xsync.o timing.o cm10a.o tty_aux.o relay_aux.o x10aux.o rfxcom.o digimax.o oregon.o -lm -lc
/usr/bin/ld: tty_aux.o:/home/normalman/Downloads/Heyu/heyu-2.10.2/tty_aux.c:112: multiple definition of `oldsb'; tty.o:/home/normalman/Downloads/Heyu/heyu-2.10.2/tty.c:116: first defined here
/usr/bin/ld: tty_aux.o:/home/normalman/Downloads/Heyu/heyu-2.10.2/tty_aux.c:112: multiple definition of `newsb'; tty.o:/home/normalman/Downloads/Heyu/heyu-2.10.2/tty.c:116: first defined here
/usr/bin/ld: relay_aux.o:/home/normalman/Downloads/Heyu/heyu-2.10.2/relay_aux.c:77: multiple definition of `spoolfile'; relay.o:/home/normalman/Downloads/Heyu/heyu-2.10.2/relay.c:81: first defined here

collect2: error: ld returned 1 exit status
make: *** [Makefile:66: heyu] Error 1

------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------

**gcc version on Manjaro**

user1@R158: /Downloads/Heyu/2.10.1/heyu-2.10.1$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC) 
user1@R158: /Downloads/Heyu/2.10.1/heyu-2.10.1$

**Comment by jkrzyszt** [comment] 2021-04-29 18:13
Closing as a duplicate of #26.

The issue has been fixed in both stable and master branches.  Go to Code, optionally select stable branch for 2.10.x based version instead of 2.11-rcX, download a ZIP and give it a try.  You can also try a master based topic/locking branch which contains a fix for device and spool file locking -- I'm waiting for poeple to report if it works for them.

Thanks,
Janusz

**Closed as completed by jkrzyszt** 2021-04-29 18:13 UTC
Labels: bug, duplicate

**Comment by btammaster** [comment] 2021-04-29 20:44
2.10.1 compiles cleanly on Mint but gets errors on Manjaro.  Am I missing something?  Apologies for being a noob.  Thank you.

**Comment by jkrzyszt** [comment] 2021-04-29 21:48
2.10.1 as well as 2.10.2 are outdated, with the build bug not fixed.  If my instructions were not clear to you, please use this link to download a snapshot of the stable branch: https://github.com/HeyuX10Automation/heyu/archive/refs/heads/stable.zip

Thanks,
Janusz

**Comment by btammaster** [comment] 2021-04-30 14:49
Success!  Thank you thank you!

Your original instructions were fine; I'm easily confused.
