### ISSUE TITLE
fedora 33 server

### ISSUE THREAD

**Issue by zonedgopher** [HeyuX10Automation/heyu#28] opened 2021-03-12 23:59 UTC
tried to install heyu-v2.11-rc3 on fedora 33 server, fresh server install. Installed on NUC7i5.
The ./configure.sh command works fine.  When I type "make" command I get an error.  I have attached a jpg of the error.
When I try to install v2.10.2 I also get an error when I run "make". I have attached a jpg of the error I get with v2.10.2 also.
I have been successfully running v2.11-rc3 on this exact same NUC running fedora 29. (I am just re-installing fedora to go from ver 29 to 33.)
Any idea what the errors mean?
Thanks
![v2 11-rc3](https://user-images.githubusercontent.com/48124695/111010585-faa4ba80-8364-11eb-9714-670786d8795f.jpg)
![v 2 10 2](https://user-images.githubusercontent.com/48124695/111010601-03958c00-8365-11eb-8994-d3035c5a5e70.jpg)

**Comment by zonedgopher** [comment] 2021-03-20 17:04
Tried the command below but did not solve my issue.  still errors.
copy of new errors below.
![20210320_130126](https://user-images.githubusercontent.com/48124695/111878035-ae690400-897c-11eb-999a-ebcb3411359e.jpg)


make CFLAGS='-fcommon'

**Comment by zonedgopher** [comment] 2021-03-20 17:31
using gcc 10.2.1

**Comment by jkrzyszt** [comment] 2021-03-24 01:45
Both issues should be now fixed in 'testing' branch, please test.

**Comment by zonedgopher** [comment] 2021-03-25 11:14
Thanks for applying a fix update. I will test.
I will post results of my testing.

**Comment by zonedgopher** [comment] 2021-03-25 12:23
The test is success.  heyu now compiles with gcc 10.2.1, and functions properly with a FTDI chipset serial/usb adapter.
Note:
The test branch was release heyu-2.11-rc3.  This is what I tested and it was success with FTDI chipset serial/usb adapter.
However, this release does not have the fix for xread.c which fixes a timing issue when using prolific chipset usb/serial adapter that causes "upload" to not work.  I added the fix below to xread.c in the test branch ( this is the same fix in xread.c in release heyu-2.10.2):
 #ifndef DARWIN
                millisleep(10);  /* Added by CWS */
#endif

I re-compiled the test branch heyu 2.11-rc3 with this patch, and the compile worked and all functions work properly with the prolific chipset usb/serial adapter, including the upload command.

At this juncture we are operating with two branches of heyu - v2.10.2 and v2.11-rc3.   The v2.10.2 has the upload timing fix but not the gcc fix.  The v2.11-rc3 has the gcc fix, but not the upload fix.  We probably need to merge these at some point now that there are two fixes.

Thanks very much for the update and fix.  I am happy to do any additional testing you might want.  However, I am limited to testing on Fedora releases 29 and 33.

**Comment by jkrzyszt** [comment] 2021-03-25 21:01
The gcc 10+ fix has been backported to 'stable' branch.  Closing as resolved.

Thanks,
Janusz

PS. @zonedgopher, I was using a pl2303 device with my main 'production' Heyu instance, and I'm still using one with a supplementary Heyu instance.  Both used to work for me without the millisleep fix.
Since the 'testing' configuration no longer defines the DARWIN symbol, the fix as is is not applicable to 'testing'.  If you are able to reproduce that issue with the 'testing' branch then please open a new ticket.

**Closed as completed by jkrzyszt** 2021-03-25 21:01 UTC
Labels: bug

**Comment by zonedgopher** [comment] 2021-03-26 12:38
When I tested the "testing" branch above, after I compiled the "testing" branch with gcc 10+, my pl2303 device with the FTDI chipset worked for the upload command.  When I replaced the pl2303 with the FTDI with the pl2303 device with the prolific chipset, the upload command stopped working.  When I switched them back it started working again with the FTDI chipset.  
My conclusion is that the timing issue is still preventing the upload command from working when using the pl2303 device with the prolific chipset .
If you want me to test a different "testing" branch, please send me a link so I can be sure I am testing the correct version.
Thanks

**Comment by jkrzyszt** [comment] 2021-03-26 20:37
Let me clarify one term I used but didn't explain its meaning, that may now mislead people reading this thread: pl2303 is a name of a Linux driver / module for usb-serial adapters based on a Prolific chipset.  For devices with a FTDI chipset there is a separate driver / module ftdi_sio.

Now @zonedgopher, you can of course use the fix from 2.10.2 with 2.11 if it resolves the upload issue for you, but a different fix needs to be developed for inclusion in 2.11.  Please do open a new ticket, then you'll receive updates on progress.   Since 'modinfo pl2303' command provides quite a long list of compatible devices, please provide as much information on your device as possible (e.g. vendor and product ID, try lsusb) in this new ticket.

EDIT: Thanks for opening the ticket, I was not aware you had done that before I responded.

Thanks,
Janusz
