### ISSUE TITLE
heyu upload fails on all versions after v2.10-rc1

### ISSUE THREAD

**Issue by zonedgopher** [HeyuX10Automation/heyu#22] opened 2020-05-10 16:53 UTC
I am posting my experience on this issue using fedora v29 on intel nuc i7 platform  - the heyu upload for cm11a fails. It gives an error "failed to erase initiator block".
Version 2.9.1 works perfectly.
version 2.94 works perfectly.
version 2.10-rc1 works perfectly
version 2.10-rc2 fails on heyu upload
version 2.10 fails on heyu upload
version 2.10.1 fails on heyu upload
version 2.11-rc3 fails on heyu upload.
Any dat you would like collected please let me know. Attached are the heyu -v upload files for version 2.9.4 that works and version 2.11-rc3 that fails.  They look identical to me, so no clue why it fails with v211rc3 and other versions listed above.
[heyu-upload-v294.txt](https://github.com/HeyuX10Automation/heyu/files/4606155/heyu-upload-v294.txt)
[heyu-upload-v211rc3.txt](https://github.com/HeyuX10Automation/heyu/files/4606156/heyu-upload-v211rc3.txt)

**Comment by zonedgopher** [comment] 2020-05-10 17:21
One additional result using ver 2.11-rc3
When I run the command "heyu turn c6 off" there is a lengthy delay (maybe about 30 secs), then I get the message " unable to send address bytes".
This command works fine with v 2.9.1, 2.9.4 and 2.10-rc1.

**Comment by arnieSkyNet** [comment] 2020-05-10 17:29
In the end I bought a 2nd hand controller from eBay and the new one worked which proved to me it’s the CMOS that’s faulty. The CMOS chip (there are two chips) stores the upload table.

So I bought I few more, 1 European mains, and I plan to get a friend to source cmos chips and replace old chips with sockets then put chips in or skip socket part.

**Comment by zonedgopher** [comment] 2020-05-10 18:42
Thanks for the reply.
I do not believe it is the controller.  Although that idea caused me to buy a back-up unit some time ago.
In all my tests (all done today), with the various versions of heyu mentioned above, I used the same physical controller unit.  It worked with the versions I indicated above and did not work with the others.  Since it worked with 3 different versions, I do not believe it to be defective.  I have also been using this same controller for a long time with ver 2.9.1, and it has been working fine.  It is working fine right now on ver 2.10-rc1.
This controller (today) works on ver 2.10-rc1 and every version before that.  It fails on every version after 2.10-rc1.
Thanks again for the comment and idea.

**Comment by arnieSkyNet** [comment] 2020-05-10 18:50
The only other suggestion (apart from the already lock messages) is compile on another hardware box the same version and see if that works.

Or install same fresh OS to new drive and compile.

**Comment by zonedgopher** [comment] 2020-05-10 20:33
I have 2 fed-29 machines.  They both are on a nuci7 hardware.  Both exhibit the exact same issue with the different versions of heyu (they each have their own controller).  I have also swapped the controllers between the two machines and the same results of upload failure occur on all versions after 2.10-rc1.  Both machines and both controllers work on ver 2.10-rc1 and earlier versions.

I believe a timing issue has been introduced somehow after ver 2.10-rc1.  Especially since the other error I get when I issue the command "heyu turn c6 on" is the error message " unable to send address bytes".  It seems the program is unable to send the data out via the USB adapter to the cm11a.  This error does not occur on ver 2.10-rc1 or earlier.  Only occurs on versions after 2.10-rc1.

**Comment by zonedgopher** [comment] 2020-05-10 20:39
Oh, I forgot to mention on thing.  On either machine, I can install ver 2.10-rc1 and heyu upload works, and commands work.  On that same machine I can then install ver 2.11-rc3, replacing ver 2.10-rc1, and upload fails and commands fail.  I can then, on the same machine, reinstall ver 2.10-rc1, over ver 2.11-rc3, and everything works again.  I can keep alternating between ver 2.10-rc1 and ver 2.11-rc3 and the reults are the same every time: ver 2.10-rc1 works and ver 2.11-rc3 fails.

**Comment by cagivacode** [comment] 2020-05-10 20:44
I agree with you on that....I did see that issue way-back-when, at that time I was running Heyu in a ubuntu 18.04 virtual machine with a usb-2-serial converter passed through. I think I was able to force the port device to a specific baud rate....to fix it. I just don't remember

I currently run heyu in a LXD ubuntu 18.04 container on a diiferent machine that has a real serial port passed through with heyu 2.10.1 which works fine (home assistant / google assistant).

**Comment by zonedgopher** [comment] 2020-05-11 00:29
Thanks for the comment about setting a specific baud rate and now having a real serial port .  I am using a usb to serial converter to connect to the cm11a, and your comment triggered me to think about the heyu faqs that mentioned the prolifics chip set is a bit flakey.  My converter uses a prolific chip set.  I have ordered another converter that uses the FTDI chip set.  Not sure if that will fix the issue, but it is worth a try.
Thanks for the comment.  You might have led me to a solution.
I will post result later.

**Comment by jkrzyszt** [comment] 2020-05-11 21:06
@zonedgopher we need to narrow down the root cause of your issue to a single commit between v2.10-rc1 and rc2, please start with this one:
https://github.com/HeyuX10Automation/heyu/archive/41725e5abbc04a36a4a3c18ebd20c17ea7e71325.zip

**Comment by zonedgopher** [comment] 2020-05-12 01:16
I downloaded the file from your link.  Here are the results - I did several iterations just to be sure I made no mistakes:
1. Re-installed heyu-2.10-rc1 to verify it works - It did work and did successfully complete an upload to cm11a.
2. Re-installed heyu-2.10-rc2 to verify failure - heyu start works - starts heyu and engine.  The heyu upload failed with the error message "failed to erase the initiator block".
3. Re-installed heyu-2.10-rc1 once again to verify it works - It did work and did successfully complete an upload to cm11a.
4. Installed the version from your link above "41725....71325.zip.  Heyu start works.  Heyu upload failed with the error message "failed to erase the initiator block".
5. Re-installed heyu-2.10-rc1 once again to verify it works - It did work and did successfully complete an upload to cm11a.
6. Re-installed the version from your link above "41725....71325.zip once again.  Heyu start works.  Heyu upload failed with the error message "failed to erase the initiator block".

I stopped at this point.

**Comment by zonedgopher** [comment] 2020-05-12 01:25
Forgot to mention, when the heyu version from your link above is installed, the command "heyu turn c6 off", stalls for about 1 minute, then gives the message "unable to send command bytes".  Yesterday, with heyu 2.11-rc3 installed, the command "heyu turn c6 off" generated the message " unable to send address bytes".  One message says address bytes and the other says command bytes.

**Comment by zonedgopher** [comment] 2020-05-12 09:47
I ran another test for v2.10-rc1 and the version from your link above.
1. On version from your link,  "41725....71325.zip, I disconnected the cm11a and ran "heyu info".
The output was: "Heyu: No response from the cm11a on /dev/ttyUSB0" & "program exiting".
2.  Connected the cm11a.  On your link ver  "41725....71325.zip, I ran "heyu info" again.  The output is below, and it says ver 2.10-rc1, but it is the version from your link above that is actually installed.  output follows:
Heyu version 2.10-rc1 
Configuration at /etc/heyu/x10.conf
Powerline interface on /dev/ttyUSB0
Firmware revision Level = 1
Interface battery usage = Unknown
Raw interface clock: Tue, Day 132, 04:26:54
(--> Civil Time: Tue 12 May 2020   05:26:54 EDT)
Uploaded schedule will expire in 234 days.
Housecode = C
0 = off, 1 = on,               unit  16.......8...4..1
Last addressed device =       0x7421 (1001000011001010)
Status of monitored devices = 0x0200 (0000000000100000)
Status of dimmed devices =    0x0208 (0000010000100000)
<end of output>

3. Re-installed ver 2.10-rc1.  (Still works totally).  I ran the command "heyu info".  Output below- actually from the 2.10-rc1 released version is the same as the one above from your link):
Heyu version 2.10-rc1
Configuration at /etc/heyu/x10.conf
Powerline interface on /dev/ttyUSB0
Firmware revision Level = 1
Interface battery usage = Unknown
Raw interface clock: Tue, Day 132, 04:32:51
(--> Civil Time: Tue 12 May 2020   05:32:51 EDT)
Uploaded schedule will expire in 234 days.
Housecode = C
0 = off, 1 = on,               unit  16.......8...4..1
Last addressed device =       0x7421 (1001000011001010)
Status of monitored devices = 0x0200 (0000000000100000)
Status of dimmed devices =    0x0208 (0000010000100000)
<end of output>
Both versions seem to be reading the cm11a.

**Comment by jkrzyszt** [comment] 2020-05-12 17:29
OK, now we know the issue was introduced not later than the commit you've tested.  Now please try this one:
https://github.com/HeyuX10Automation/heyu/archive/5461658d800667fbb3d5311a6b8fa9f5eced5c81.zip

**Comment by zonedgopher** [comment] 2020-05-12 18:05
1. Installed heyu-5461658d800667fbb3d5311a6b8fa9f5eced5c81.zip (2nd test ver).
2. "heyu start" worked.
3. " heyu upload" failed with same message as failures above.   "failed to erase the initiator block"
4. "heyu info" reads the cm11a, same as other failed tests above.
5.  "heyu turn c6 off" stalls for about 1 minute and reports " unable to send address bytes".
Done

**Comment by jkrzyszt** [comment] 2020-05-12 22:24
@zonedgopher, thanks for help. It looks like potential regression was introduced by the commit you've just tested:
https://github.com/HeyuX10Automation/heyu/commit/5461658d800667fbb3d5311a6b8fa9f5eced5c81

Here is a fix applied on top of v2.11-rc3:
https://github.com/jkrzyszt/heyu/archive/topic/upload_issues.zip
Can you please test it?

@Henry Butz: if you are still reading the heyu_users group, would it be possible for you to test the above fix on Darwin?  I'm asking for that because the fix reverts the following commit which addressed a issue on Darwin that you reported:
https://github.com/HeyuX10Automation/heyu/commit/6352911c2026b47a46aea7ac98376accc8a8612f352911c2026b47a46aea7ac98376accc8a8612f

Thanks,
Janusz

**Comment by jkrzyszt** [comment] 2020-05-12 22:51
@zonedgopher, can you please also report exact linux kernel version you are using?

Thanks,
Janusz

**Comment by zonedgopher** [comment] 2020-05-12 23:38
Ok.
https://github.com/jkrzyszt/heyu/archive/topic/upload_issues.zip
I installed the version of heyu from the above zip.
It was installed over version 2.10-rc1 (the working version).
It worked perfectly.
heyu start worked
heyu upload worked
heyu info reported version 2.11-rc3
heyu turn c6 off worked.

My kernel is : 5.3.11-100.fc29.x86_64

I would appreciate knowing what was changed to make it work.  Was it a timing issue for the usb /serial port?

Also, can I use the version I just tested as the new  ver 2.11-rc3, or will you release a new verison?

Thanks for the help.

**Comment by zonedgopher** [comment] 2020-05-13 00:02
I thought it was included in my last message? Let me know if it is not there,  i will send it. Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by zonedgopher** [comment] 2020-05-13 12:50
As info, I have opened a new issue related to normal user permissions being lost after a re-boot.

**Comment by zonedgopher** [comment] 2020-05-13 15:42
Update for the v2.11-rc3 upload issue:
I received the new usb-serial adapter (Gearmo brand) that uses the FTDI chipset.  (The one I have been using for the above tests is a Trendnet prolific adapter).

With this new FTDI adapter, the current/original release of heyu v2.11-rc3 works fine with no problems.  The new adapter also works with the patched ver of 2.11-rc3 which you sent to me above.
So, the issue can also be resolved by using an FTDI chipset adapter instead of a prolific adapter.  However, for compatibility with both adapters, it is best to leave in the fix (millisleep) you just added to v2.11-rc3.
Perhaps this will be useful info for someone.

**Comment by jkrzyszt** [comment] 2020-05-14 21:13
The issue has been addressed in stable version 2.10.2 just released.

Since build system has been changed significantly for v2.11-rc pre-releases, the same workaround may be not applicable for 2.11 as that might introduce a regression on Darwin (OS/X) by effectively reverting https://github.com/HeyuX10Automation/heyu/commit/6352911c2026b47a46aea7ac98376accc8a8612f .  If there are any Heyu users running that platform, please test if https://github.com/jkrzyszt/heyu/archive/topic/upload_issues.zip still works for you.  Once confirmed, I'll be happy to integrate the fix into 2.11, if not then I'll try to work out a different solution.

Thanks,
Janusz

**Closed by jkrzyszt** 2020-05-14 21:13 UTC

**Comment by zonedgopher** [comment] 2020-05-15 01:54
Thank you for your assistance on both of my posted issues.
